### PR TITLE
recipe rewritten to support compiled library

### PR DESCRIPTION
**Pull request by dvd0101**
This is a followup of the conversation on conan-io/wishlist#26

This is my first conan package and unfortunately I cannot test it under osx nor windows

### CODE REVIEW

**Comment by memsharded** [comment]
Hi!
Thanks for this PR, it is interesting, but CI is failing. I'll have a look at it when possible (now I am out of office, it might take a week).

Also, it is not necessary to remove the header only option, we could use an option to let consumers opt for the header only or the compiled version. It is very easy, I will take your changes and try to come up with a solution for both approaches. Thanks very much!

**Comment by dvd0101** [comment]
It fails with

```
python build.py
Traceback (most recent call last):
  File "build.py", line 6, in <module>
    builder.add_common_builds()
  File "C:\Python27\lib\site-packages\conan\packager.py", line 124, in add_common_builds
    if self.mingw_builds(pure_c):
  File "C:\Python27\lib\site-packages\conan\packager.py", line 95, in mingw_builds
    version, arch, exception, thread = config
ValueError: need more than 1 value to unpack
Command exited with code 1
```

probably I should change update build.py with something like:
`builder.add_common_builds(shared_option_name="fmt:shared", pure_c=False)`

IMHO the header only option has zero benefits over the compiled; in the case of fmt this option exists to simplify the setup of the library, but this job is better handled by conan itself

**Comment by memsharded** [comment]
Yes, I agree, the header-only has little benefit over the compiled for normal use. But as setting it up is trivial in the conan-package, and there might be some user that could prefer the header-only (e.g., they have a different build system and compiler, and the standard fmt CMakeLists does not handle they settings), they still would be able to use it with the header-only version and their not common development environment.

**Comment by dvd0101** [comment]
Ok, but please make the header version not the default

**Comment by memsharded** [comment]
Hi!
I have pushed some changes I had in a branch for the dual header-only/compiled option:https://github.com/memsharded/conan-fmt/blob/testing/conanfile.py

Of course, the compiled one is the default, the header-only should be only for those rare cases.

I have just check your PR, and realized that you have a fPIC option too. I guess that you are thinking about embedding the static version of fmt into a shared library, right? I will add it too.

Also, what is failing in CI is the build of conan-package-tools, it seems a bug in conan-package-tools, I will check it when possible and try to submit a PR to fix it. Thanks again for your help!

**Comment by dvd0101** [comment]
TY (and yes the fpic is needed exactly for you say, fmtlib/fmt#290)

**Comment by memsharded** [comment]
I have added the fPIC option (removing it in windows), pushed to https://github.com/memsharded/conan-fmt, CI only passes in OSX. I will check now for Win and Linux.

**Comment by memsharded** [comment]
I have submitted a PR to fix the CI issue in windows: https://github.com/conan-io/conan-package-tools/pull/24

Added more support for windows compiled libraries (handling MD, MT, etc runtimes)

CI now pass in travis (Linux, OSX for several compilers): https://travis-ci.org/memsharded/conan-fmt/builds/152220479

**Comment by memsharded** [comment]
Passed CI on appveyor for windows, reverting to a previous conan-package-tools version (0.2.16). 
https://ci.appveyor.com/project/memsharded/conan-fmt/build/1.0.11

So I'd say that the fmt package starts to be more stable, compiled for a few dozens different configurations in Win, Linux, Mac. Please try it (the binaries too) if possible and tell me. Thanks very much for your contribution!

**Comment by memsharded** [comment]
This was solved a long ago, now the binary is the default conf, and building for many configs. I have also just added support for shared libraries (still failing in windows), but working on it. I think this PR can be closed, thanks again!

**Pull request closed without merging**
